#!/bin/sh
# Regenerate Sources/VF64Metal/Validation/M9ExpSmokeVectors.swift from the
# pinned MPFR oracle. The selection is deterministic: every special value, then
# every 37th boundary case, for each of the five rounding modes.
set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_dir=$(CDPATH= cd -- "$script_dir/../.." && pwd)
generator=$("$repo_dir/scripts/bootstrap-mpfr.sh" | tail -n 1)
output="$repo_dir/Sources/VF64Metal/Validation/M9ExpSmokeVectors.swift"

{
    printf '// Generated by tools/m9/generate-smoke-vectors.sh from the pinned MPFR\n'
    printf '// oracle. Do not edit by hand.\n\n'
    printf 'let m9ExpSmokeVectors: [String: [(UInt64, UInt64, UInt8)]] = [\n'
    for rounding in rnear_even rminMag rmin rmax rnear_maxMag; do
        printf '    "%s": [\n' "$rounding"
        "$generator" "$rounding" boundary |
            awk 'NR <= 14 || (NR - 14) % 37 == 0 {
                printf "        (0x%s, 0x%s, 0x%s),\n", $1, $2, $3
            }'
        printf '    ],\n'
    done
    printf ']\n'
} > "$output"

printf 'wrote %s\n' "$output"
