#!/usr/bin/env python3
"""Emit the M9 pow constant block for Shaders/Math/Pow.metal.

Constants are soft_wide3 literals: value = (-1)^sign * sig * 2^(exponent-192)
with sig in [2^191, 2^192), truncated toward zero, so each representation
error is below 2^-191 relative and of known sign.

Usage: python3 tools/m9/generate-pow-constants.py
"""
from decimal import Decimal, getcontext

getcontext().prec = 160

# log2(m) = (2/ln2) * s * sum_{k=0..K} z^k / (2k+1), z = s^2, |s| <= 0.1716.
TERMS = 37
S_MAX = (Decimal(2).sqrt() - 1) / (Decimal(2).sqrt() + 1)
MASK = (1 << 64) - 1


def wide3(value: Decimal) -> str:
    sign = 1 if value < 0 else 0
    magnitude = -value if value < 0 else value
    exponent = 0
    while magnitude >= 1:
        magnitude /= 2
        exponent += 1
    while magnitude < Decimal("0.5"):
        magnitude *= 2
        exponent -= 1
    sig = int(magnitude * (Decimal(2) ** 192))
    assert 1 << 191 <= sig < 1 << 192
    return (
        f"soft_wide3{{0x{sig >> 128:016x}ul, 0x{(sig >> 64) & MASK:016x}ul, "
        f"0x{sig & MASK:016x}ul, {exponent}, {'true' if sign else 'false'}}}"
    )


def main() -> None:
    ln2 = Decimal(2).ln()
    print("// Generated by tools/m9/generate-pow-constants.py. Do not edit by hand.")
    print(f"constant soft_wide3 SOFT_POW_TWO_OVER_LN2 = {wide3(2 / ln2)};")
    print(f"constant int SOFT_POW_LOG_TERMS = {TERMS};")
    print(f"constant soft_wide3 SOFT_POW_ATANH_COEFFICIENT[{TERMS + 1}] = {{")
    for k in range(TERMS + 1):
        print(f"    {wide3(Decimal(1) / (2 * k + 1))},  // 1/{2 * k + 1}")
    print("};")
    z = S_MAX * S_MAX
    tail = sum(z ** k / (2 * k + 1) for k in range(TERMS + 1, TERMS + 120))
    print(f"// truncated atanh tail: < 2^{tail.ln() / Decimal(2).ln():.1f} relative")


if __name__ == "__main__":
    main()
