#!/usr/bin/env python3
"""Emit the M9 log-family constant block for Shaders/Math/Log.metal.

Every constant is a soft_wide literal: value = (-1)^sign * sig * 2^(exponent-128)
with sig in [2^127, 2^128), truncated toward zero exactly as in
generate-exp-constants.py, so each representation error is below 2^-127
relative and of known sign.

Usage: python3 tools/m9/generate-log-constants.py
"""
from decimal import Decimal, getcontext

getcontext().prec = 120

# atanh series terms: 2 atanh(s) = 2s * sum_{k=0..K} z^k / (2k+1), z = s^2.
ATANH_TERMS = 24
S_MAX = (Decimal(2).sqrt() - 1) / (Decimal(2).sqrt() + 1)


def encode(value: Decimal) -> tuple[int, int, int]:
    sign = 1 if value < 0 else 0
    magnitude = -value if value < 0 else value
    exponent = 0
    while magnitude >= 1:
        magnitude /= 2
        exponent += 1
    while magnitude < Decimal("0.5"):
        magnitude *= 2
        exponent -= 1
    sig = int(magnitude * (Decimal(2) ** 128))
    assert 1 << 127 <= sig < 1 << 128, (sig, exponent)
    return sig, exponent, sign


def wide(value: Decimal) -> str:
    sig, exponent, sign = encode(value)
    return (
        f"soft_wide{{0x{sig >> 64:016x}ul, 0x{sig & ((1 << 64) - 1):016x}ul, "
        f"{exponent}, {'true' if sign else 'false'}}}"
    )


def main() -> None:
    ln2 = Decimal(2).ln()
    sqrt2 = Decimal(2).sqrt()
    print("// Generated by tools/m9/generate-log-constants.py. Do not edit by hand.")
    print(f"constant soft_wide SOFT_LOG_LN2 = {wide(ln2)};")
    print(f"constant soft_wide SOFT_LOG_INV_LN2 = {wide(1 / ln2)};")
    print(f"constant soft_wide SOFT_CBRT_ONE_THIRD = {wide(Decimal(1) / 3)};")
    # sqrt(2) truncated to 128 bits. sqrt(2) is irrational, so a wide
    # significand is at least sqrt(2) exactly when it exceeds this one.
    print(f"constant soft_wide SOFT_LOG_SQRT2 = {wide(sqrt2)};")
    print()
    print(f"constant int SOFT_LOG_ATANH_TERMS = {ATANH_TERMS};")
    print(f"constant soft_wide SOFT_LOG_ATANH_COEFFICIENT[{ATANH_TERMS + 1}] = {{")
    for k in range(ATANH_TERMS + 1):
        print(f"    {wide(Decimal(1) / (2 * k + 1))},  // 1/{2 * k + 1}")
    print("};")
    z = S_MAX * S_MAX
    tail = sum(z ** k / (2 * k + 1) for k in range(ATANH_TERMS + 1, ATANH_TERMS + 80))
    print()
    print(f"// truncated atanh tail at |s| <= (sqrt2-1)/(sqrt2+1): < 2^{tail.ln() / Decimal(2).ln():.1f}")


if __name__ == "__main__":
    main()
