#!/bin/sh
# Regenerate Sources/VF64Metal/Validation/M9SmokeVectors.swift from the pinned
# MPFR oracle. The selection is deterministic: for each function and each of
# the five rounding modes, every special value and then every 37th boundary
# case (every 11th for hypot, whose boundary corpus is mostly special pairs).
set -eu

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_dir=$(CDPATH= cd -- "$script_dir/../.." && pwd)
generator=$("$repo_dir/scripts/bootstrap-mpfr.sh" | tail -n 1)
output="$repo_dir/Sources/VF64Metal/Validation/M9SmokeVectors.swift"

{
    printf '// Generated by tools/m9/generate-smoke-vectors.sh from the pinned MPFR\n'
    printf '// oracle. Do not edit by hand. Each vector is (a, b, result, flags);\n'
    printf '// b is zero for unary functions.\n\n'
    printf 'let m9SmokeVectors: [String: [String: [(UInt64, UInt64, UInt64, UInt8)]]] = [\n'
    for function in f64_exp f64_exp2 f64_expm1 f64_log f64_log2 f64_log1p f64_cbrt f64_hypot; do
        printf '    "%s": [\n' "$function"
        for rounding in rnear_even rminMag rmin rmax rnear_maxMag; do
            printf '        "%s": [\n' "$rounding"
            if [ "$function" = f64_hypot ]; then
                "$generator" "$function" "$rounding" boundary |
                    awk 'NR % 11 == 0 {
                        printf "            (0x%s, 0x%s, 0x%s, 0x%s),\n", $1, $2, $3, $4
                    }'
            else
                "$generator" "$function" "$rounding" boundary |
                    awk 'NR <= 14 || (NR - 14) % 37 == 0 {
                        printf "            (0x%s, 0x0, 0x%s, 0x%s),\n", $1, $2, $3
                    }'
            fi
            printf '        ],\n'
        done
        printf '    ],\n'
    done
    printf ']\n'
} > "$output"

printf 'wrote %s\n' "$output"
