#!/usr/bin/env python3
"""Emit the M9 exp constant block for Sources/VF64Metal/Shaders/Math/Exp.metal.

Every constant is a soft_wide literal: value = (-1)^sign * sig * 2^(exponent-128)
with sig in [2^127, 2^128). Significands are truncated toward zero, which keeps
the sign of each constant's representation error known and reproducible.

Usage: python3 tools/m9/generate-exp-constants.py
"""
from decimal import Decimal, getcontext

getcontext().prec = 120

TERMS = 30
LN2_HI_BITS = 40


def encode(value: Decimal) -> tuple[int, int, int]:
    """Return (sig, exponent, sign) with sig truncated to 128 bits."""
    if value == 0:
        return 0, 0, 0
    sign = 1 if value < 0 else 0
    magnitude = -value if value < 0 else value
    exponent = 0
    while magnitude >= 1:
        magnitude /= 2
        exponent += 1
    while magnitude < Decimal("0.5"):
        magnitude *= 2
        exponent -= 1
    sig = int(magnitude * (Decimal(2) ** 128))
    if sig >= 1 << 128:  # only reachable from decimal rounding at the top edge
        sig >>= 1
        exponent += 1
    assert 1 << 127 <= sig < 1 << 128, (sig, exponent)
    return sig, exponent, sign


def literal(name: str, value: Decimal) -> str:
    sig, exponent, sign = encode(value)
    return (
        f"constant soft_wide {name} = soft_wide{{"
        f"0x{sig >> 64:016x}ul, 0x{sig & ((1 << 64) - 1):016x}ul, "
        f"{exponent}, {'true' if sign else 'false'}}};"
    )


def main() -> None:
    ln2 = Decimal(2).ln()
    # ln2_hi keeps LN2_HI_BITS significant bits so that k * ln2_hi is exact in a
    # 128-bit significand for every reachable |k| < 2^11.
    scale = Decimal(2) ** LN2_HI_BITS
    ln2_hi = Decimal(int(ln2 * scale)) / scale
    ln2_lo = ln2 - ln2_hi

    print("// Generated by tools/m9/generate-exp-constants.py. Do not edit by hand.")
    print(f"// ln2 split: {LN2_HI_BITS} leading bits in the high term.")
    print(literal("SOFT_EXP_INV_LN2", 1 / ln2))
    print(literal("SOFT_EXP_LN2_HI", ln2_hi))
    print(literal("SOFT_EXP_LN2_LO", ln2_lo))
    print()
    print(f"constant int SOFT_EXP_TERMS = {TERMS};")
    print(f"constant soft_wide SOFT_EXP_RECIPROCAL_FACTORIAL[{TERMS + 1}] = {{")
    factorial = Decimal(1)
    for n in range(TERMS + 1):
        if n > 0:
            factorial *= n
        sig, exponent, sign = encode(1 / factorial)
        print(
            f"    soft_wide{{0x{sig >> 64:016x}ul, 0x{sig & ((1 << 64) - 1):016x}ul, "
            f"{exponent}, {'true' if sign else 'false'}}},  // 1/{n}!"
        )
    print("};")

    # Reported so the error budget in docs can be checked against the source.
    tail = (Decimal("0.3466") ** (TERMS + 1))
    for n in range(2, TERMS + 2):
        tail /= n
    print()
    print(f"// truncated Taylor tail at |r| <= ln2/2: < 2^{tail.ln() / Decimal(2).ln():.1f}")


if __name__ == "__main__":
    main()
