#!/usr/bin/env python3
"""Emit the M9 inverse-trigonometric constant block for Shaders/Math/Atan.metal.

Constants are soft_wide literals truncated toward zero, as in
generate-exp-constants.py. atan is evaluated in Decimal by argument halving,
atan(x) = 2 atan(x / (1 + sqrt(1 + x^2))), then its Taylor series, and pi is
cross-checked against Machin's formula.

Usage: python3 tools/m9/generate-atan-constants.py
"""
from decimal import Decimal, getcontext

getcontext().prec = 130

TABLE = 16          # atan(j/16), j = 0..16
SERIES_TERMS = 13   # atan(t) = t * sum_{k=0..13} (-1)^k t^(2k) / (2k+1)
T_MAX = Decimal(1) / 32


def atan(x: Decimal) -> Decimal:
    if x == 0:
        return Decimal(0)
    halvings = 0
    while abs(x) > Decimal("0.01"):
        x = x / (1 + (1 + x * x).sqrt())
        halvings += 1
    total, term, k = Decimal(0), x, 0
    while True:
        piece = term / (2 * k + 1)
        if abs(piece) < Decimal(10) ** -125:
            break
        total += piece if k % 2 == 0 else -piece
        term *= x * x
        k += 1
    return total * (2 ** halvings)


def encode(value: Decimal) -> tuple[int, int, int]:
    sign = 1 if value < 0 else 0
    magnitude = -value if value < 0 else value
    exponent = 0
    while magnitude >= 1:
        magnitude /= 2
        exponent += 1
    while magnitude < Decimal("0.5"):
        magnitude *= 2
        exponent -= 1
    sig = int(magnitude * (Decimal(2) ** 128))
    assert 1 << 127 <= sig < 1 << 128, (sig, exponent)
    return sig, exponent, sign


def wide(value: Decimal) -> str:
    if value == 0:
        return "soft_wide{0x0000000000000000ul, 0x0000000000000000ul, 0, false}"
    sig, exponent, sign = encode(value)
    return (
        f"soft_wide{{0x{sig >> 64:016x}ul, 0x{sig & ((1 << 64) - 1):016x}ul, "
        f"{exponent}, {'true' if sign else 'false'}}}"
    )


def main() -> None:
    pi = 4 * atan(Decimal(1))
    machin = 16 * atan(Decimal(1) / 5) - 4 * atan(Decimal(1) / 239)
    assert abs(pi - machin) < Decimal(10) ** -110
    print("// Generated by tools/m9/generate-atan-constants.py. Do not edit by hand.")
    print(f"constant soft_wide SOFT_ATAN_PI = {wide(pi)};")
    print(f"constant soft_wide SOFT_ATAN_PI_2 = {wide(pi / 2)};")
    print(f"constant soft_wide SOFT_ATAN_PI_4 = {wide(pi / 4)};")
    print(f"constant soft_wide SOFT_ATAN_3PI_4 = {wide(3 * pi / 4)};")
    print()
    print(f"constant soft_wide SOFT_ATAN_TABLE[{TABLE + 1}] = {{")
    for j in range(TABLE + 1):
        print(f"    {wide(atan(Decimal(j) / TABLE))},  // atan({j}/{TABLE})")
    print("};")
    print(f"constant int SOFT_ATAN_SERIES_TERMS = {SERIES_TERMS};")
    z = T_MAX * T_MAX
    tail = z ** (SERIES_TERMS + 1) / (2 * SERIES_TERMS + 3)
    print(f"// truncated series tail at |t| <= 1/32: < 2^{tail.ln() / Decimal(2).ln():.1f} relative")


if __name__ == "__main__":
    main()
