// M9 correctly rounded binary64 atan, atan2, asin, and acos.
//
// Every function reduces to atan(w) for a wide 0 <= w <= 1:
//
//     atan(w) = atan(c) + atan(t),  c = j/16, j = round(16 w),
//     t = (w - c) / (1 + w c),      |t| <= 1/32,
//     atan(t) = t * sum_{k=0..13} (-1)^k t^(2k) / (2k+1).
//
// The series tail is below 2^-144.9 relative. w - c and 1 + w c are exact
// when w is a binary64 value (atan); for a wide quotient they truncate by under
// 2^-128 absolute, below 2^-122 relative to atan(w) >= atan(1/32) when j >= 1.
// The division adds 2^-124.6 relative to t, and the Horner sum, damped by
// t^2 <= 2^-10, under 2^-126. The table and pi constants carry 2^-127 each.
// A relative error e in w moves atan(w) by at most e relative, since
// atan(w) >= (pi/4) w on [0, 1]. Arguments above 1 use pi/2 - atan(1/w), and
// x < 0 in atan2 and acos uses pi - atan(...): both results are at least
// pi/4, bounding the amplification by 3. Every path stays below 2^-120
// relative, against the 2^-116 certification margin.
//
// Results near the argument are decided in closed form because the offset is
// cubic: atan(x) = x - x^3/3 and asin(x) = x + x^3/6 lie within x^2/3 of x,
// inside half an ulp only for |x| < 2^-27. For atan2 with x > 0 and
// |y/x| < 2^-55, the exact quotient q = y/x is rounded with exact integer
// division instead: q is rational with a 53-bit denominator, so when it is not
// on a rounding boundary it is at least 2^-109 relative away from one, while
// atan(q) differs from q by under 2^-111.6 relative, always toward zero.
// No other result is exactly representable or a midpoint: atan, asin, and acos
// of a nonzero algebraic number are transcendental.

// Generated by tools/m9/generate-atan-constants.py. Do not edit by hand.
constant soft_wide SOFT_ATAN_PI = soft_wide{0xc90fdaa22168c234ul, 0xc4c6628b80dc1cd1ul, 2, false};
constant soft_wide SOFT_ATAN_PI_2 = soft_wide{0xc90fdaa22168c234ul, 0xc4c6628b80dc1cd1ul, 1, false};
constant soft_wide SOFT_ATAN_PI_4 = soft_wide{0xc90fdaa22168c234ul, 0xc4c6628b80dc1cd1ul, 0, false};
constant soft_wide SOFT_ATAN_3PI_4 = soft_wide{0x96cbe3f9990e91a7ul, 0x9394c9e8a0a5159cul, 2, false};

constant soft_wide SOFT_ATAN_TABLE[17] = {
    soft_wide{0x0000000000000000ul, 0x0000000000000000ul, 0, false},  // atan(0/16)
    soft_wide{0xffaaddb967ef4e36ul, 0xcb2792dc0e2e0d51ul, -4, false},  // atan(1/16)
    soft_wide{0xfeadd4d5617b6e32ul, 0xc897989f3e888ef7ul, -3, false},  // atan(2/16)
    soft_wide{0xbdcbda5e72d81134ul, 0x7b0b4f881c9c7487ul, -2, false},  // atan(3/16)
    soft_wide{0xfadbafc96406eb15ul, 0x6dc79ef5f7a217e5ul, -2, false},  // atan(4/16)
    soft_wide{0x9b13b9b83f5e5e69ul, 0xc5abb498d27af328ul, -1, false},  // atan(5/16)
    soft_wide{0xb7b0ca0f26f78473ul, 0x8aa32122dcfe4483ul, -1, false},  // atan(6/16)
    soft_wide{0xd327761e611fe5b6ul, 0x427c95e9001e7136ul, -1, false},  // atan(7/16)
    soft_wide{0xed63382b0dda7b45ul, 0x6fe445ecbc3a8d03ul, -1, false},  // atan(8/16)
    soft_wide{0x832bf4a6d9867e2aul, 0x4b6a09cb61a515c0ul, 0, false},  // atan(9/16)
    soft_wide{0x8f005d5ef7f59f9bul, 0x5c835e1665c43747ul, 0, false},  // atan(10/16)
    soft_wide{0x9a2f80e671bdda20ul, 0x4226f8e2204ff3bcul, 0, false},  // atan(11/16)
    soft_wide{0xa4bc7d1934f70924ul, 0x19a87f2a457dac9eul, 0, false},  // atan(12/16)
    soft_wide{0xaeac4c38b4d8c080ul, 0x14725e2f3e52070aul, 0, false},  // atan(13/16)
    soft_wide{0xb8053e2bc2319e73ul, 0xcb2da55210a4443dul, 0, false},  // atan(14/16)
    soft_wide{0xc0ce85b8ac526640ul, 0x89dd62c46e92fa24ul, 0, false},  // atan(15/16)
    soft_wide{0xc90fdaa22168c234ul, 0xc4c6628b80dc1cd1ul, 0, false},  // atan(16/16)
};
constant int SOFT_ATAN_SERIES_TERMS = 13;
// truncated series tail at |t| <= 1/32: < 2^-144.9 relative

// atan(w) for 0 <= w <= 1.
inline soft_wide soft_atan_reduced(soft_wide w) {
    int j = soft_wide_round_to_int(soft_wide_scale2(w, 4));
    soft_wide t = w;
    if (j != 0) {
        soft_wide c = soft_wide_scale2(soft_wide_from_int(j), -4);
        t = soft_wide_div(
            soft_wide_sub(w, c),
            soft_wide_add(soft_wide_one(), soft_wide_mul(w, c))
        );
    }
    soft_wide z = soft_wide_mul(t, t);
    soft_wide accumulator = SOFT_LOG_ATANH_COEFFICIENT[SOFT_ATAN_SERIES_TERMS];
    for (int term = SOFT_ATAN_SERIES_TERMS - 1; term >= 0; --term) {
        accumulator = soft_wide_sub(
            SOFT_LOG_ATANH_COEFFICIENT[term], soft_wide_mul(z, accumulator)
        );
    }
    return soft_wide_add(SOFT_ATAN_TABLE[j], soft_wide_mul(t, accumulator));
}

// atan(num / den) for num, den >= 0, not both zero.
inline soft_wide soft_atan_ratio(soft_wide num, soft_wide den) {
    if (soft_wide_magnitude_greater(num, den)) {
        return soft_wide_sub(SOFT_ATAN_PI_2, soft_atan_reduced(soft_wide_div(den, num)));
    }
    return soft_atan_reduced(soft_wide_div(num, den));
}

// sqrt by r <- r + r (1 - d r^2) / 2 from an FP32 seed, as in hypot: three
// quadratic steps reach 2^-125, and the final product adds 2^-127.
inline soft_wide soft_wide_sqrt(soft_wide d) {
    if (soft_wide_is_zero(d)) return d;
    soft_wide r = soft_wide_inverse_root_seed(d, 2);
    soft_wide one = soft_wide_one();
    for (int step = 0; step < 3; ++step) {
        soft_wide square = soft_wide_mul(soft_wide_mul(r, r), d);
        r = soft_wide_add(r, soft_wide_scale2(soft_wide_mul(r, soft_wide_sub(one, square)), -1));
    }
    return soft_wide_mul(d, r);
}

inline soft_wide soft_wide_negate_if(soft_wide a, bool negative) {
    if (negative && !soft_wide_is_zero(a)) a.sign = !a.sign;
    return a;
}

// |x| < 2^-27, nonzero: exponent fields below 1023 - 27.
constant uint soft_atan_tiny_exponent_field = 996u;

inline ulong soft_atan64_certified(
    ulong a, uint roundingMode, thread uint &flags, thread bool &certified
) {
    certified = true;
    uint exponentField = uint((a >> 52) & 0x7fful);
    bool sign = (a >> 63) != 0ul;
    if (soft_is_nan(a)) {
        if (soft_is_signaling_nan(a)) flags |= soft_flag_invalid;
        return a | 0x0008000000000000ul;
    }
    if ((a & 0x7ffffffffffffffful) == 0ul) return a;
    if ((a & 0x7ffffffffffffffful) == 0x7ff0000000000000ul) {
        return soft_wide_to_f64_status(
            soft_wide_negate_if(SOFT_ATAN_PI_2, sign), roundingMode, flags, certified
        );
    }
    // atan(x) = x - x^3/3 + ...: strictly toward zero from x.
    if (exponentField < soft_atan_tiny_exponent_field) {
        return soft_round_beside(a, sign, roundingMode, flags);
    }
    soft_wide x = soft_wide_from_f64(a & 0x7ffffffffffffffful);
    soft_wide result = exponentField < 1023u
        ? soft_atan_reduced(x)
        : (a & 0x7ffffffffffffffful) == 0x3ff0000000000000ul
            ? SOFT_ATAN_PI_4
            : soft_wide_sub(SOFT_ATAN_PI_2, soft_atan_reduced(soft_wide_reciprocal(x)));
    return soft_wide_to_f64_status(
        soft_wide_negate_if(result, sign), roundingMode, flags, certified
    );
}

// Rounds sign * (|y| / |x| - epsilon) for 0 < epsilon < 2^-111 |y/x|, by
// exact restoring division: R = floor(MY / MX 2^56) has at least 56 bits, and
// the true value lies strictly inside (R, R + 1) units, or just below R when
// the division is exact.
inline ulong soft_round_quotient_toward_zero(
    ulong yMagnitude, ulong xMagnitude, bool sign, uint roundingMode,
    thread uint &flags
) {
    soft_normalized y = soft_normalize_operand(
        uint(yMagnitude >> 52), yMagnitude & 0x000ffffffffffffful
    );
    soft_normalized x = soft_normalize_operand(
        uint(xMagnitude >> 52), xMagnitude & 0x000ffffffffffffful
    );
    ulong remainder = y.significand;
    ulong quotient = 0ul;
    for (int bit = 0; bit < 57; ++bit) {
        quotient <<= 1;
        if (remainder >= x.significand) {
            remainder -= x.significand;
            quotient |= 1ul;
        }
        remainder <<= 1;
    }
    if (remainder == 0ul) quotient -= 1ul;
    return soft_wide_exact_to_f64_status(
        soft_wide_from_root(
            soft_u128{0ul, quotient}, true, y.exponent - x.exponent - 56, sign
        ),
        roundingMode, flags
    );
}

// atan2(y, x). Zeros and infinities follow IEEE 754-2019 9.2.1 (C99 Annex F).
inline ulong soft_atan2_64_certified(
    ulong y, ulong x, uint roundingMode, thread uint &flags, thread bool &certified
) {
    certified = true;
    if (soft_is_nan(y) || soft_is_nan(x)) {
        if (soft_is_signaling_nan(y) || soft_is_signaling_nan(x)) {
            flags |= soft_flag_invalid;
        }
        return soft_propagate_nan(y, x);
    }
    bool ySign = (y >> 63) != 0ul;
    bool xSign = (x >> 63) != 0ul;
    ulong yMagnitude = y & 0x7ffffffffffffffful;
    ulong xMagnitude = x & 0x7ffffffffffffffful;
    bool yInfinite = yMagnitude == 0x7ff0000000000000ul;
    bool xInfinite = xMagnitude == 0x7ff0000000000000ul;

    soft_wide result;
    if (yMagnitude == 0ul) {
        if (!xSign) return y;
        result = SOFT_ATAN_PI;
    } else if (xMagnitude == 0ul) {
        result = SOFT_ATAN_PI_2;
    } else if (yInfinite) {
        result = !xInfinite ? SOFT_ATAN_PI_2 : (xSign ? SOFT_ATAN_3PI_4 : SOFT_ATAN_PI_4);
    } else if (xInfinite) {
        if (!xSign) return ySign ? 0x8000000000000000ul : 0ul;
        result = SOFT_ATAN_PI;
    } else {
        soft_wide yw = soft_wide_from_f64(yMagnitude);
        soft_wide xw = soft_wide_from_f64(xMagnitude);
        if (!xSign && soft_wide_magnitude_greater(xw, soft_wide_scale2(yw, 55))) {
            return soft_round_quotient_toward_zero(
                yMagnitude, xMagnitude, ySign, roundingMode, flags
            );
        }
        result = soft_atan_ratio(yw, xw);
        if (xSign) result = soft_wide_sub(SOFT_ATAN_PI, result);
    }
    return soft_wide_to_f64_status(
        soft_wide_negate_if(result, ySign), roundingMode, flags, certified
    );
}

// sqrt(1 - x^2) from the exact factors 1 - x and 1 + x.
inline soft_wide soft_asin_cosine(soft_wide x) {
    soft_wide one = soft_wide_one();
    return soft_wide_sqrt(soft_wide_mul(soft_wide_sub(one, x), soft_wide_add(one, x)));
}

inline ulong soft_asin64_certified(
    ulong a, uint roundingMode, thread uint &flags, thread bool &certified
) {
    certified = true;
    uint exponentField = uint((a >> 52) & 0x7fful);
    bool sign = (a >> 63) != 0ul;
    ulong magnitude = a & 0x7ffffffffffffffful;
    if (soft_is_nan(a)) {
        if (soft_is_signaling_nan(a)) flags |= soft_flag_invalid;
        return a | 0x0008000000000000ul;
    }
    if (magnitude == 0ul) return a;
    if (magnitude > 0x3ff0000000000000ul) {
        flags |= soft_flag_invalid;
        return 0x7ff8000000000000ul;
    }
    // asin(x) = x + x^3/6 + ...: strictly away from zero from x.
    if (exponentField < soft_atan_tiny_exponent_field) {
        return soft_round_beside(a, !sign, roundingMode, flags);
    }
    soft_wide x = soft_wide_from_f64(magnitude);
    soft_wide result = soft_atan_ratio(x, soft_asin_cosine(x));
    return soft_wide_to_f64_status(
        soft_wide_negate_if(result, sign), roundingMode, flags, certified
    );
}

inline ulong soft_acos64_certified(
    ulong a, uint roundingMode, thread uint &flags, thread bool &certified
) {
    certified = true;
    bool sign = (a >> 63) != 0ul;
    ulong magnitude = a & 0x7ffffffffffffffful;
    if (soft_is_nan(a)) {
        if (soft_is_signaling_nan(a)) flags |= soft_flag_invalid;
        return a | 0x0008000000000000ul;
    }
    if (magnitude > 0x3ff0000000000000ul) {
        flags |= soft_flag_invalid;
        return 0x7ff8000000000000ul;
    }
    if (a == 0x3ff0000000000000ul) return 0ul;
    soft_wide x = soft_wide_from_f64(magnitude);
    soft_wide result = soft_atan_ratio(soft_asin_cosine(x), x);
    if (sign) result = soft_wide_sub(SOFT_ATAN_PI, result);
    return soft_wide_to_f64_status(result, roundingMode, flags, certified);
}
