// M9 correctly rounded binary64 exponential.
//
// exp(x) = 2^k * exp(r) with k = round(x / ln2) and r = x - k*ln2.
//
// The reduction is a Cody-Waite split: ln2_hi carries 40 significant bits, so
// k*ln2_hi is exact in a 128-bit significand for every reachable |k| < 2^11,
// and x - k*ln2_hi is exact as well because it is a multiple of 2^-54 below
// 2^11. Only the k*ln2_lo term is inexact, contributing an absolute error
// below 2^-155 to r, which is a relative error of the same size in the result.
//
// exp(r) is a 30-term Taylor sum evaluated by Horner in the wide format. The
// truncated tail is below 2^-160 at |r| <= ln2/2, and the 60 truncating wide
// operations contribute below 2^-121, so the evaluation error stays under
// 2^-120. Scaling by 2^k is exact, being an exponent adjustment.
//
// The result is certified per call: soft_wide_to_f64_status reports whether
// the wide value is farther from the deciding rounding boundary than 2^-116
// relative, which bounds the evaluation error with margin to spare. A
// certified result is correctly rounded. An uncertified result is reported,
// never silently returned as if it were proven. See
// docs/milestones/M9-transcendentals.md for the proof-obligation states.

// Generated by tools/m9/generate-exp-constants.py. Do not edit by hand.
// ln2 split: 40 leading bits in the high term.
constant soft_wide SOFT_EXP_INV_LN2 = soft_wide{0xb8aa3b295c17f0bbul, 0xbe87fed0691d3e88ul, 1, false};
constant soft_wide SOFT_EXP_LN2_HI = soft_wide{0xb17217f7d1000000ul, 0x0000000000000000ul, 0, false};
constant soft_wide SOFT_EXP_LN2_LO = soft_wide{0xcf79abc9e3b39803ul, 0xf2f6af40f3432672ul, -40, false};

constant int SOFT_EXP_TERMS = 30;
constant soft_wide SOFT_EXP_RECIPROCAL_FACTORIAL[31] = {
    soft_wide{0x8000000000000000ul, 0x0000000000000000ul, 1, false},  // 1/0!
    soft_wide{0x8000000000000000ul, 0x0000000000000000ul, 1, false},  // 1/1!
    soft_wide{0x8000000000000000ul, 0x0000000000000000ul, 0, false},  // 1/2!
    soft_wide{0xaaaaaaaaaaaaaaaaul, 0xaaaaaaaaaaaaaaaaul, -2, false},  // 1/3!
    soft_wide{0xaaaaaaaaaaaaaaaaul, 0xaaaaaaaaaaaaaaaaul, -4, false},  // 1/4!
    soft_wide{0x8888888888888888ul, 0x8888888888888888ul, -6, false},  // 1/5!
    soft_wide{0xb60b60b60b60b60bul, 0x60b60b60b60b60b6ul, -9, false},  // 1/6!
    soft_wide{0xd00d00d00d00d00dul, 0x00d00d00d00d00d0ul, -12, false},  // 1/7!
    soft_wide{0xd00d00d00d00d00dul, 0x00d00d00d00d00d0ul, -15, false},  // 1/8!
    soft_wide{0xb8ef1d2ab6399c7dul, 0x560e4472800b8ef1ul, -18, false},  // 1/9!
    soft_wide{0x93f27dbbc4fae397ul, 0x780b69f5333c725bul, -21, false},  // 1/10!
    soft_wide{0xd7322b3faa271c7ful, 0x3a3f25c1bee38f10ul, -25, false},  // 1/11!
    soft_wide{0x8f76c77fc6c4bdaaul, 0x26d4c3d67f425f60ul, -28, false},  // 1/12!
    soft_wide{0xb092309d43684be5ul, 0x1c198e91d7b4269dul, -32, false},  // 1/13!
    soft_wide{0xc9cba54603e4e905ul, 0xd6f8a2efd1f27546ul, -36, false},  // 1/14!
    soft_wide{0xd73f9f399dc0f88eul, 0xc32b58774657f48ful, -40, false},  // 1/15!
    soft_wide{0xd73f9f399dc0f88eul, 0xc32b58774657f48ful, -44, false},  // 1/16!
    soft_wide{0xca963b81856a5359ul, 0x3028cbbb8d7ff53bul, -48, false},  // 1/17!
    soft_wide{0xb413c31dcbecbbddul, 0x8024435161554bc3ul, -52, false},  // 1/18!
    soft_wide{0x97a4da340a0ab926ul, 0x50f61dbdcb3a5abful, -56, false},  // 1/19!
    soft_wide{0xf2a15d201011283dul, 0x4e5695fc785d5dfeul, -61, false},  // 1/20!
    soft_wide{0xb8dc77b6e7ab8c5ful, 0x78a37e77372290c2ul, -65, false},  // 1/21!
    soft_wide{0x8671cb6dbfc294a2ul, 0x86485bf99c763abbul, -69, false},  // 1/22!
    soft_wide{0xbb0da098b1c0cecbul, 0xdc3826ebfb13cc26ul, -74, false},  // 1/23!
    soft_wide{0xf96780cb97abbe65ul, 0x25a033e54ec51033ul, -79, false},  // 1/24!
    soft_wide{0x9f9e66e8b2fd46a7ul, 0x22520cbbb7885c49ul, -83, false},  // 1/25!
    soft_wide{0xc4742fe35272cd1cul, 0x790285d3580a4a33ul, -88, false},  // 1/26!
    soft_wide{0xe8d58e16e6751905ul, 0x4d0c78aea13b9a50ul, -93, false},  // 1/27!
    soft_wide{0x850c5131a842e9b9ul, 0xe2e28e1aa546a152ul, -97, false},  // 1/28!
    soft_wide{0x92cfcc5a1ac56bd5ul, 0xf1873bb378948eb3ul, -102, false},  // 1/29!
    soft_wide{0x9c9962823eb07306ul, 0x56f6a614c4e2ba58ul, -107, false},  // 1/30!
};

// truncated Taylor tail at |r| <= ln2/2: < 2^-160.1

// Reduction and Horner evaluation for the main path: finite arguments with
// 2^-60 <= |x| < 1024. Every special case is decided before this is reached.
inline soft_wide soft_exp64_wide(ulong a) {
    soft_wide x = soft_wide_from_f64(a);
    int k = soft_wide_round_to_int(soft_wide_mul(x, SOFT_EXP_INV_LN2));
    soft_wide scaled = soft_wide_from_int(k);
    soft_wide r = soft_wide_sub(x, soft_wide_mul(scaled, SOFT_EXP_LN2_HI));
    r = soft_wide_sub(r, soft_wide_mul(scaled, SOFT_EXP_LN2_LO));

    soft_wide accumulator = SOFT_EXP_RECIPROCAL_FACTORIAL[SOFT_EXP_TERMS];
    for (int term = SOFT_EXP_TERMS - 1; term >= 0; --term) {
        accumulator = soft_wide_add(
            SOFT_EXP_RECIPROCAL_FACTORIAL[term], soft_wide_mul(r, accumulator)
        );
    }
    return soft_wide_scale2(accumulator, k);
}

// |x| < 2^-60 is handled in closed form. There exp(x) lies strictly between
// 1 - 2^-59 and 1 + 2^-59 and is never exactly 1 for x != 0 (Lindemann), so
// the result is 1 or its neighbour, decided by the rounding mode and sign.
// The binary64 neighbours of 1 are 2^-53 below and 2^-52 above, both far
// outside that interval, so no other value is reachable.
constant uint soft_exp_tiny_exponent_field = 963u;  // 1023 - 60

inline ulong soft_exp64_certified(
    ulong a, uint roundingMode, thread uint &flags, thread bool &certified
) {
    certified = true;
    uint exponentField = uint((a >> 52) & 0x7fful);
    ulong fraction = a & 0x000ffffffffffffful;
    bool sign = (a >> 63) != 0ul;

    if (exponentField == 0x7ffu) {
        if (fraction != 0ul) {
            if (soft_is_signaling_nan(a)) flags |= soft_flag_invalid;
            return soft_propagate_nan(a, a);
        }
        return sign ? 0ul : 0x7ff0000000000000ul;
    }
    if (exponentField == 0u && fraction == 0ul) return 0x3ff0000000000000ul;

    if (exponentField < soft_exp_tiny_exponent_field) {
        flags |= soft_flag_inexact;
        bool above = !sign;
        if (roundingMode == soft_round_near_even ||
            roundingMode == soft_round_near_max_mag) {
            return 0x3ff0000000000000ul;
        }
        if (roundingMode == soft_round_max) {
            return above ? 0x3ff0000000000001ul : 0x3ff0000000000000ul;
        }
        // Toward zero and toward negative infinity agree on a positive result.
        return above ? 0x3ff0000000000000ul : 0x3feffffffffffffful;
    }

    // |x| >= 1024 cannot be reduced by this path and is decided by range.
    // exp(1024) overflows binary64 and exp(-1024) is below half the smallest
    // subnormal, so both results follow from the rounding mode alone.
    if (exponentField >= 1033u) {
        flags |= soft_flag_inexact;
        if (!sign) {
            flags |= soft_flag_overflow;
            return soft_overflow_result(false, roundingMode);
        }
        flags |= soft_flag_underflow;
        return roundingMode == soft_round_max ? 1ul : 0ul;
    }

    return soft_wide_to_f64_status(
        soft_exp64_wide(a), roundingMode, flags, certified
    );
}

// Bit 5 is not an IEEE exception. It is a VF64 M9 extension that reports a
// result whose rounding this implementation could not prove for that argument,
// so that a caller using the flags API instead of the certification argument
// still cannot mistake an unproven result for a proven one.
constant uint soft_flag_uncertified = 32;

inline ulong soft_exp64_status(ulong a, uint roundingMode, thread uint &flags) {
    bool certified = true;
    ulong result = soft_exp64_certified(a, roundingMode, flags, certified);
    if (!certified) flags |= soft_flag_uncertified;
    return result;
}

// The convenience forms discard both the exception flags and the certificate,
// matching the M2 rule for its own flag-free wrappers: valid only where the
// caller's contract observes neither.
inline ulong soft_exp64_mode(ulong a, uint roundingMode) {
    uint ignoredFlags = 0u;
    return soft_exp64_status(a, roundingMode, ignoredFlags);
}

inline ulong soft_exp64(ulong a) {
    return soft_exp64_mode(a, soft_round_near_even);
}
