// M9 correctly rounded binary64 log, log2, and log1p.
//
// A positive wide argument u is split as u = m 2^e with m in [sqrt2/2, sqrt2),
// and log(m) = 2 atanh(s) with s = (m - 1) / (m + 1), |s| <= 0.1716:
//
//     2 atanh(s) = 2s * sum_{k=0..24} z^k / (2k + 1),  z = s^2.
//
// The truncated tail is below 2^-132.8 relative. s carries the division's
// relative error, below 2^-124.6; the Horner sum stays in [1, 1.0103] and its
// 48 truncating operations are damped by |z| < 2^-5, contributing below
// 2^-125; the final product adds 2^-127. So log(m) has relative error below
// 2^-123.5.
//
// The full result adds e ln2 (or e itself for log2). The 128-bit ln2 and
// 1/ln2 constants and their products each contribute 2^-127 relative. When
// e = +-1 the two terms can partly cancel, but |log m| <= 0.347 against
// |e ln2| >= 0.693 bounds the amplification by 3, and it shrinks as |e|
// grows. Every path therefore stays below 2^-121 relative, against the
// 2^-116 certification margin.
//
// Exact results are decided in closed form, because a value on the binary64
// grid cannot be certified in a directed mode: log(1) = +0, log2(2^e) = e, and
// log1p(0) = 0. Every other result is irrational (Lindemann, Gelfond-
// Schneider), so it is never exactly on the grid or exactly halfway.

// Generated by tools/m9/generate-log-constants.py. Do not edit by hand.
constant soft_wide SOFT_LOG_LN2 = soft_wide{0xb17217f7d1cf79abul, 0xc9e3b39803f2f6aful, 0, false};
constant soft_wide SOFT_LOG_INV_LN2 = soft_wide{0xb8aa3b295c17f0bbul, 0xbe87fed0691d3e88ul, 1, false};
constant soft_wide SOFT_CBRT_ONE_THIRD = soft_wide{0xaaaaaaaaaaaaaaaaul, 0xaaaaaaaaaaaaaaaaul, -1, false};
constant soft_wide SOFT_LOG_SQRT2 = soft_wide{0xb504f333f9de6484ul, 0x597d89b3754abe9ful, 1, false};

constant int SOFT_LOG_ATANH_TERMS = 24;
constant soft_wide SOFT_LOG_ATANH_COEFFICIENT[25] = {
    soft_wide{0x8000000000000000ul, 0x0000000000000000ul, 1, false},  // 1/1
    soft_wide{0xaaaaaaaaaaaaaaaaul, 0xaaaaaaaaaaaaaaaaul, -1, false},  // 1/3
    soft_wide{0xccccccccccccccccul, 0xccccccccccccccccul, -2, false},  // 1/5
    soft_wide{0x9249249249249249ul, 0x2492492492492492ul, -2, false},  // 1/7
    soft_wide{0xe38e38e38e38e38eul, 0x38e38e38e38e38e3ul, -3, false},  // 1/9
    soft_wide{0xba2e8ba2e8ba2e8bul, 0xa2e8ba2e8ba2e8baul, -3, false},  // 1/11
    soft_wide{0x9d89d89d89d89d89ul, 0xd89d89d89d89d89dul, -3, false},  // 1/13
    soft_wide{0x8888888888888888ul, 0x8888888888888888ul, -3, false},  // 1/15
    soft_wide{0xf0f0f0f0f0f0f0f0ul, 0xf0f0f0f0f0f0f0f0ul, -4, false},  // 1/17
    soft_wide{0xd79435e50d79435eul, 0x50d79435e50d7943ul, -4, false},  // 1/19
    soft_wide{0xc30c30c30c30c30cul, 0x30c30c30c30c30c3ul, -4, false},  // 1/21
    soft_wide{0xb21642c8590b2164ul, 0x2c8590b21642c859ul, -4, false},  // 1/23
    soft_wide{0xa3d70a3d70a3d70aul, 0x3d70a3d70a3d70a3ul, -4, false},  // 1/25
    soft_wide{0x97b425ed097b425eul, 0xd097b425ed097b42ul, -4, false},  // 1/27
    soft_wide{0x8d3dcb08d3dcb08dul, 0x3dcb08d3dcb08d3dul, -4, false},  // 1/29
    soft_wide{0x8421084210842108ul, 0x4210842108421084ul, -4, false},  // 1/31
    soft_wide{0xf83e0f83e0f83e0ful, 0x83e0f83e0f83e0f8ul, -5, false},  // 1/33
    soft_wide{0xea0ea0ea0ea0ea0eul, 0xa0ea0ea0ea0ea0eaul, -5, false},  // 1/35
    soft_wide{0xdd67c8a60dd67c8aul, 0x60dd67c8a60dd67cul, -5, false},  // 1/37
    soft_wide{0xd20d20d20d20d20dul, 0x20d20d20d20d20d2ul, -5, false},  // 1/39
    soft_wide{0xc7ce0c7ce0c7ce0cul, 0x7ce0c7ce0c7ce0c7ul, -5, false},  // 1/41
    soft_wide{0xbe82fa0be82fa0beul, 0x82fa0be82fa0be82ul, -5, false},  // 1/43
    soft_wide{0xb60b60b60b60b60bul, 0x60b60b60b60b60b6ul, -5, false},  // 1/45
    soft_wide{0xae4c415c9882b931ul, 0x0572620ae4c415c9ul, -5, false},  // 1/47
    soft_wide{0xa72f05397829cbc1ul, 0x4e5e0a72f0539782ul, -5, false},  // 1/49
};

// truncated atanh tail at |s| <= (sqrt2-1)/(sqrt2+1): < 2^-132.8

// log(m) for m in [sqrt2/2, sqrt2), given f = m - 1.
inline soft_wide soft_log_reduced(soft_wide f, soft_wide m) {
    soft_wide s = soft_wide_div(f, soft_wide_add(m, soft_wide_one()));
    soft_wide z = soft_wide_mul(s, s);
    soft_wide accumulator = SOFT_LOG_ATANH_COEFFICIENT[SOFT_LOG_ATANH_TERMS];
    for (int term = SOFT_LOG_ATANH_TERMS - 1; term >= 0; --term) {
        accumulator = soft_wide_add(
            SOFT_LOG_ATANH_COEFFICIENT[term], soft_wide_mul(z, accumulator)
        );
    }
    return soft_wide_scale2(soft_wide_mul(s, accumulator), 1);
}

// Splits a positive wide u into m in [sqrt2/2, sqrt2) and e with u = m 2^e.
inline soft_wide soft_log_split(soft_wide u, thread int &e) {
    // u = (significand / 2^127) 2^(exponent - 1), the fraction in [1, 2).
    e = u.exponent - 1;
    u.exponent = 1;
    if (soft_wide_magnitude_greater(u, SOFT_LOG_SQRT2)) {
        u.exponent = 0;
        e += 1;
    }
    return u;
}

// Shared special values for log and log2. Returns true when decided.
inline bool soft_log_special(ulong a, thread ulong &result, thread uint &flags) {
    bool sign = (a >> 63) != 0ul;
    if (soft_is_nan(a)) {
        if (soft_is_signaling_nan(a)) flags |= soft_flag_invalid;
        result = a | 0x0008000000000000ul;
        return true;
    }
    if ((a & 0x7ffffffffffffffful) == 0ul) {
        flags |= soft_flag_infinite;
        result = 0xfff0000000000000ul;
        return true;
    }
    if (sign) {
        flags |= soft_flag_invalid;
        result = 0x7ff8000000000000ul;
        return true;
    }
    if (a == 0x7ff0000000000000ul) {
        result = a;
        return true;
    }
    return false;
}

inline ulong soft_log64_certified(
    ulong a, uint roundingMode, thread uint &flags, thread bool &certified
) {
    certified = true;
    ulong special;
    if (soft_log_special(a, special, flags)) return special;
    if (a == 0x3ff0000000000000ul) return 0ul;

    int e;
    soft_wide m = soft_log_split(soft_wide_from_f64(a), e);
    // m carries at most 53 significant bits, so m - 1 is exact.
    soft_wide result = soft_log_reduced(soft_wide_sub(m, soft_wide_one()), m);
    if (e != 0) {
        result = soft_wide_add(
            soft_wide_mul(soft_wide_from_int(e), SOFT_LOG_LN2), result
        );
    }
    return soft_wide_to_f64_status(result, roundingMode, flags, certified);
}

inline ulong soft_log2_64_certified(
    ulong a, uint roundingMode, thread uint &flags, thread bool &certified
) {
    certified = true;
    ulong special;
    if (soft_log_special(a, special, flags)) return special;

    int e;
    soft_wide m = soft_log_split(soft_wide_from_f64(a), e);
    soft_wide f = soft_wide_sub(m, soft_wide_one());
    if (soft_wide_is_zero(f)) {
        // A power of two: the integer e is exact in binary64.
        return soft_wide_exact_to_f64_status(
            soft_wide_from_int(e), roundingMode, flags
        );
    }
    soft_wide result = soft_wide_mul(soft_log_reduced(f, m), SOFT_LOG_INV_LN2);
    if (e != 0) result = soft_wide_add(soft_wide_from_int(e), result);
    return soft_wide_to_f64_status(result, roundingMode, flags, certified);
}

// log1p(x) for nonzero |x| < 2^-60 lies strictly below x and within
// x^2/2 < 2^-61 |x| of it, far inside half an ulp, so it is decided by the
// rounding mode alone.
inline ulong soft_log1p64_certified(
    ulong a, uint roundingMode, thread uint &flags, thread bool &certified
) {
    certified = true;
    uint exponentField = uint((a >> 52) & 0x7fful);
    bool sign = (a >> 63) != 0ul;
    if (soft_is_nan(a)) {
        if (soft_is_signaling_nan(a)) flags |= soft_flag_invalid;
        return a | 0x0008000000000000ul;
    }
    if ((a & 0x7ffffffffffffffful) == 0ul) return a;
    if (a == 0xbff0000000000000ul) {
        flags |= soft_flag_infinite;
        return 0xfff0000000000000ul;
    }
    if (sign && (a & 0x7ffffffffffffffful) > 0x3ff0000000000000ul) {
        flags |= soft_flag_invalid;  // x < -1, including -infinity
        return 0x7ff8000000000000ul;
    }
    if (a == 0x7ff0000000000000ul) return a;
    if (exponentField < soft_exp_tiny_exponent_field) {
        return soft_round_beside(a, false, roundingMode, flags);
    }

    // u = 1 + x is exact for |x| < 2^75: the argument has no bits below
    // 2^-112, so 1 + x spans at most 113 bits, or at most 76 bits once
    // x >= 1. Above 2^75 the sum is truncated by under 2^-127 relative, an
    // absolute error below 2^-127 in a result above 51.
    soft_wide x = soft_wide_from_f64(a);
    int e;
    soft_wide m = soft_log_split(soft_wide_add(soft_wide_one(), x), e);
    // With e = 0, m = 1 + x and m - 1 = x exactly. Otherwise the result is at
    // least 0.34 in magnitude and m - 1 needs only absolute accuracy.
    soft_wide f = e == 0 ? x : soft_wide_sub(m, soft_wide_one());
    soft_wide result = soft_log_reduced(f, m);
    if (e != 0) {
        result = soft_wide_add(
            soft_wide_mul(soft_wide_from_int(e), SOFT_LOG_LN2), result
        );
    }
    return soft_wide_to_f64_status(result, roundingMode, flags, certified);
}
