// M9 correctly rounded binary64 pow.
//
// Write |x| = m 2^e with m in [sqrt2/2, sqrt2), and z = y log2|x| = y e + y L
// with L = log2(m). Then |x|^y = 2^k exp2(r) with k = round(z), r = z - k.
//
// L comes from the 192-bit format: s = (m - 1) / (m + 1) to 2^-189, the
// 38-term atanh sum (tail below 2^-199.5, Horner damped by s^2 < 2^-5), and
// the 192-bit 2/ln2, so L is within 2^-186 relative. Since m is chosen in
// [sqrt2/2, sqrt2), |e + L| >= |e|/2, so |y L| <= |z| and the products need
// no cancellation analysis. y e is exact. z is therefore within
// 2^11 * 2^-186 = 2^-175 absolute for every |z| < 2048, and r = z - k is
// exact. r is truncated to 128 bits (2^-129 absolute) and exp2(r) evaluated
// on the exp polynomial as in exp2, within 2^-119.9 relative. The result is
// within 2^-119.8 relative, against the 2^-116 certification margin.
//
// pow is not transcendental on every input: x^y is rational, and may then be
// exactly representable or exactly halfway, when |x| = X 2^E (X odd) is a
// perfect 2^k-th power and y = n / 2^k. With X > 1 that needs X >= 3^(2^k),
// so k <= 5, and y > 0. Those cases are computed exactly in integers and
// rounded exactly; every other x^y is irrational or a non-dyadic rational
// and is evaluated as above.

// Generated by tools/m9/generate-pow-constants.py. Do not edit by hand.
constant soft_wide3 SOFT_POW_TWO_OVER_LN2 = soft_wide3{0xb8aa3b295c17f0bbul, 0xbe87fed0691d3e88ul, 0xeb577aa8dd695a58ul, 2, false};
constant int SOFT_POW_LOG_TERMS = 37;
constant soft_wide3 SOFT_POW_ATANH_COEFFICIENT[38] = {
    soft_wide3{0x8000000000000000ul, 0x0000000000000000ul, 0x0000000000000000ul, 1, false},  // 1/1
    soft_wide3{0xaaaaaaaaaaaaaaaaul, 0xaaaaaaaaaaaaaaaaul, 0xaaaaaaaaaaaaaaaaul, -1, false},  // 1/3
    soft_wide3{0xccccccccccccccccul, 0xccccccccccccccccul, 0xccccccccccccccccul, -2, false},  // 1/5
    soft_wide3{0x9249249249249249ul, 0x2492492492492492ul, 0x4924924924924924ul, -2, false},  // 1/7
    soft_wide3{0xe38e38e38e38e38eul, 0x38e38e38e38e38e3ul, 0x8e38e38e38e38e38ul, -3, false},  // 1/9
    soft_wide3{0xba2e8ba2e8ba2e8bul, 0xa2e8ba2e8ba2e8baul, 0x2e8ba2e8ba2e8ba2ul, -3, false},  // 1/11
    soft_wide3{0x9d89d89d89d89d89ul, 0xd89d89d89d89d89dul, 0x89d89d89d89d89d8ul, -3, false},  // 1/13
    soft_wide3{0x8888888888888888ul, 0x8888888888888888ul, 0x8888888888888888ul, -3, false},  // 1/15
    soft_wide3{0xf0f0f0f0f0f0f0f0ul, 0xf0f0f0f0f0f0f0f0ul, 0xf0f0f0f0f0f0f0f0ul, -4, false},  // 1/17
    soft_wide3{0xd79435e50d79435eul, 0x50d79435e50d7943ul, 0x5e50d79435e50d79ul, -4, false},  // 1/19
    soft_wide3{0xc30c30c30c30c30cul, 0x30c30c30c30c30c3ul, 0x0c30c30c30c30c30ul, -4, false},  // 1/21
    soft_wide3{0xb21642c8590b2164ul, 0x2c8590b21642c859ul, 0x0b21642c8590b216ul, -4, false},  // 1/23
    soft_wide3{0xa3d70a3d70a3d70aul, 0x3d70a3d70a3d70a3ul, 0xd70a3d70a3d70a3dul, -4, false},  // 1/25
    soft_wide3{0x97b425ed097b425eul, 0xd097b425ed097b42ul, 0x5ed097b425ed097bul, -4, false},  // 1/27
    soft_wide3{0x8d3dcb08d3dcb08dul, 0x3dcb08d3dcb08d3dul, 0xcb08d3dcb08d3dcbul, -4, false},  // 1/29
    soft_wide3{0x8421084210842108ul, 0x4210842108421084ul, 0x2108421084210842ul, -4, false},  // 1/31
    soft_wide3{0xf83e0f83e0f83e0ful, 0x83e0f83e0f83e0f8ul, 0x3e0f83e0f83e0f83ul, -5, false},  // 1/33
    soft_wide3{0xea0ea0ea0ea0ea0eul, 0xa0ea0ea0ea0ea0eaul, 0x0ea0ea0ea0ea0ea0ul, -5, false},  // 1/35
    soft_wide3{0xdd67c8a60dd67c8aul, 0x60dd67c8a60dd67cul, 0x8a60dd67c8a60dd6ul, -5, false},  // 1/37
    soft_wide3{0xd20d20d20d20d20dul, 0x20d20d20d20d20d2ul, 0x0d20d20d20d20d20ul, -5, false},  // 1/39
    soft_wide3{0xc7ce0c7ce0c7ce0cul, 0x7ce0c7ce0c7ce0c7ul, 0xce0c7ce0c7ce0c7cul, -5, false},  // 1/41
    soft_wide3{0xbe82fa0be82fa0beul, 0x82fa0be82fa0be82ul, 0xfa0be82fa0be82faul, -5, false},  // 1/43
    soft_wide3{0xb60b60b60b60b60bul, 0x60b60b60b60b60b6ul, 0x0b60b60b60b60b60ul, -5, false},  // 1/45
    soft_wide3{0xae4c415c9882b931ul, 0x0572620ae4c415c9ul, 0x882b9310572620aeul, -5, false},  // 1/47
    soft_wide3{0xa72f05397829cbc1ul, 0x4e5e0a72f0539782ul, 0x9cbc14e5e0a72f05ul, -5, false},  // 1/49
    soft_wide3{0xa0a0a0a0a0a0a0a0ul, 0xa0a0a0a0a0a0a0a0ul, 0xa0a0a0a0a0a0a0a0ul, -5, false},  // 1/51
    soft_wide3{0x9a90e7d95bc609a9ul, 0x0e7d95bc609a90e7ul, 0xd95bc609a90e7d95ul, -5, false},  // 1/53
    soft_wide3{0x94f2094f2094f209ul, 0x4f2094f2094f2094ul, 0xf2094f2094f2094ful, -5, false},  // 1/55
    soft_wide3{0x8fb823ee08fb823eul, 0xe08fb823ee08fb82ul, 0x3ee08fb823ee08fbul, -5, false},  // 1/57
    soft_wide3{0x8ad8f2fba9386822ul, 0xb63cbeea4e1a08adul, 0x8f2fba9386822b63ul, -5, false},  // 1/59
    soft_wide3{0x864b8a7de6d1d608ul, 0x64b8a7de6d1d6086ul, 0x4b8a7de6d1d60864ul, -5, false},  // 1/61
    soft_wide3{0x8208208208208208ul, 0x2082082082082082ul, 0x0820820820820820ul, -5, false},  // 1/63
    soft_wide3{0xfc0fc0fc0fc0fc0ful, 0xc0fc0fc0fc0fc0fcul, 0x0fc0fc0fc0fc0fc0ul, -6, false},  // 1/65
    soft_wide3{0xf4898d5f85bb3950ul, 0x3d226357e16ece54ul, 0x0f4898d5f85bb395ul, -6, false},  // 1/67
    soft_wide3{0xed7303b5cc0ed730ul, 0x3b5cc0ed7303b5ccul, 0x0ed7303b5cc0ed73ul, -6, false},  // 1/69
    soft_wide3{0xe6c2b4481cd85689ul, 0x039b0ad12073615aul, 0x240e6c2b4481cd85ul, -6, false},  // 1/71
    soft_wide3{0xe070381c0e070381ul, 0xc0e070381c0e0703ul, 0x81c0e070381c0e07ul, -6, false},  // 1/73
    soft_wide3{0xda740da740da740dul, 0xa740da740da740daul, 0x740da740da740da7ul, -6, false},  // 1/75
};
// truncated atanh tail: < 2^-199.5 relative

// log2(m) for binary64-derived m in [sqrt2/2, sqrt2), within 2^-186.
inline soft_wide3 soft_pow_log2_reduced(soft_wide m) {
    soft_wide3 mw = soft_wide3_from_wide(m);
    soft_wide3 one = soft_wide3_one();
    soft_wide3 s = soft_wide3_div(soft_wide3_sub(mw, one), soft_wide3_add(mw, one));
    soft_wide3 z = soft_wide3_mul(s, s);
    soft_wide3 accumulator = SOFT_POW_ATANH_COEFFICIENT[SOFT_POW_LOG_TERMS];
    for (int term = SOFT_POW_LOG_TERMS - 1; term >= 0; --term) {
        accumulator = soft_wide3_add(
            SOFT_POW_ATANH_COEFFICIENT[term], soft_wide3_mul(z, accumulator)
        );
    }
    return soft_wide3_mul(soft_wide3_mul(s, accumulator), SOFT_POW_TWO_OVER_LN2);
}

// Exact integer square root of v < 2^63, or false if v is not a square.
inline bool soft_pow_exact_sqrt(ulong v, thread ulong &root) {
    ulong r = ulong(sqrt(float(v)));
    for (int step = 0; step < 64 && r * r > v; ++step) --r;
    for (int step = 0; step < 64 && (r + 1ul) * (r + 1ul) <= v; ++step) ++r;
    root = r;
    return r * r == v;
}

// A^n into a 128-bit integer, or false on overflow.
inline bool soft_pow_integer_power(ulong base, uint n, thread soft_u128 &power) {
    soft_u128 result = soft_u128{0ul, 1ul};
    for (uint i = 0; i < n; ++i) {
        // result * base, with base < 2^53: overflow when the high part grows
        // past 2^128.
        ulong low = result.lo * base;
        ulong carry = mulhi(result.lo, base);
        ulong highLow = result.hi * base;
        if (mulhi(result.hi, base) != 0ul) return false;
        ulong high = highLow + carry;
        if (high < highLow) return false;
        result = soft_u128{high, low};
    }
    power = result;
    return true;
}

// Rounds |x|^y exactly when it is rational and dyadic: x a perfect 2^k-th
// power and y = n / 2^k with n > 0, or x a power of two with E y an integer.
// Returns false when x^y is irrational or not dyadic.
inline bool soft_pow_exact(
    ulong xMagnitude, ulong yBits, bool negative, uint roundingMode,
    thread uint &flags, thread ulong &result
) {
    soft_normalized xn = soft_normalize_operand(
        uint(xMagnitude >> 52), xMagnitude & 0x000ffffffffffffful
    );
    uint xZeros = uint(ctz(xn.significand));
    ulong oddX = xn.significand >> xZeros;
    int powerX = xn.exponent - 1075 + int(xZeros);

    ulong yMagnitude = yBits & 0x7ffffffffffffffful;
    bool yNegative = (yBits >> 63) != 0ul;
    soft_normalized yn = soft_normalize_operand(
        uint(yMagnitude >> 52), yMagnitude & 0x000ffffffffffffful
    );
    uint yZeros = uint(ctz(yn.significand));
    ulong oddY = yn.significand >> yZeros;
    int powerY = yn.exponent - 1075 + int(yZeros);  // y = oddY 2^powerY

    if (oddX == 1ul) {
        // |x|^y = 2^(E y): dyadic exactly when E y is an integer. |E y| at or
        // beyond 4096 overflows or underflows, and is saturated there.
        if (powerX == 0) return false;  // |x| = 1 is decided earlier
        long scaled = long(powerX);
        if (powerY < 0) {
            uint k = uint(-powerY);
            if (k > 11u || (powerX % (1 << k)) != 0) return false;
            scaled /= long(1 << k);
        }
        long exponent = 4096;
        if (oddY < 4096ul && powerY < 13) {
            exponent = min(scaled * long(oddY << uint(max(powerY, 0))), 4096l);
            exponent = max(exponent, -4096l);
        } else if (scaled < 0) {
            exponent = -4096;
        }
        if (yNegative) exponent = -exponent;
        soft_wide value = soft_wide_scale2(soft_wide_one(), int(exponent));
        value.sign = negative;
        result = soft_wide_exact_to_f64_status(value, roundingMode, flags);
        return true;
    }
    if (yNegative) return false;  // 1 / X^n with X odd > 1 is not dyadic
    uint k = powerY < 0 ? uint(-powerY) : 0u;
    if (k > 5u) return false;
    ulong root = oddX;
    for (uint step = 0; step < k; ++step) {
        if (!soft_pow_exact_sqrt(root, root)) return false;
    }
    if (k > 0u && (powerX % (1 << k)) != 0) return false;
    int rootPower = powerX / (1 << k);
    if (powerY > 7) return false;  // n >= 2^7: A^n exceeds 128 bits for A >= 3
    ulong n = oddY << uint(max(powerY, 0));
    if (n > 128ul) return false;
    soft_u128 power;
    if (!soft_pow_integer_power(root, uint(n), power)) return false;
    soft_wide value = soft_wide_from_root(power, false, rootPower * int(n), negative);
    result = soft_wide_exact_to_f64_status(value, roundingMode, flags);
    return true;
}

// Integer classification of a finite y: 0 not an integer, 1 even, 2 odd.
inline uint soft_pow_integer_kind(ulong y) {
    uint exponentField = uint((y >> 52) & 0x7fful);
    ulong fraction = y & 0x000ffffffffffffful;
    if ((y & 0x7ffffffffffffffful) == 0ul) return 1u;
    if (exponentField < 1023u) return 0u;
    if (exponentField > 1075u) return 1u;
    uint fractionBits = 1075u - exponentField;  // bits below the units bit
    ulong significand = fraction | (1ul << 52);
    if (fractionBits == 0u) return (significand & 1ul) != 0ul ? 2u : 1u;
    if ((significand & ((1ul << fractionBits) - 1ul)) != 0ul) return 0u;
    return ((significand >> fractionBits) & 1ul) != 0ul ? 2u : 1u;
}

// Special values follow IEEE 754-2019 9.2.1; signaling NaNs raise invalid
// and propagate as in M2, including pow(sNaN, 0) and pow(1, sNaN).
inline ulong soft_pow64_certified(
    ulong x, ulong y, uint roundingMode, thread uint &flags, thread bool &certified
) {
    certified = true;
    if (soft_is_signaling_nan(x) || soft_is_signaling_nan(y)) {
        flags |= soft_flag_invalid;
        return soft_propagate_nan(x, y);
    }
    ulong xMagnitude = x & 0x7ffffffffffffffful;
    ulong yMagnitude = y & 0x7ffffffffffffffful;
    bool xNegative = (x >> 63) != 0ul;
    bool yNegative = (y >> 63) != 0ul;
    const ulong one = 0x3ff0000000000000ul;
    const ulong infinity = 0x7ff0000000000000ul;
    if (yMagnitude == 0ul || x == one) return one;
    if (soft_is_nan(x) || soft_is_nan(y)) return soft_propagate_nan(x, y);

    bool yInfinite = yMagnitude == infinity;
    uint kind = yInfinite ? 1u : soft_pow_integer_kind(y);
    bool oddInteger = kind == 2u;
    if (yInfinite) {
        if (xMagnitude == one) return one;  // pow(-1, +-inf)
        bool above = xMagnitude > one;      // |x| > 1, including infinities
        return (above != yNegative) ? infinity : 0ul;
    }
    if (xMagnitude == 0ul) {
        ulong signBit = (xNegative && oddInteger) ? 0x8000000000000000ul : 0ul;
        if (yNegative) {
            flags |= soft_flag_infinite;
            return signBit | infinity;
        }
        return signBit;
    }
    if (xMagnitude == infinity) {
        ulong signBit = (xNegative && oddInteger) ? 0x8000000000000000ul : 0ul;
        return signBit | (yNegative ? 0ul : infinity);
    }
    if (xNegative && kind == 0u) {
        flags |= soft_flag_invalid;
        return 0x7ff8000000000000ul;
    }
    bool negative = xNegative && oddInteger;
    if (xMagnitude == one) return negative ? (one | 0x8000000000000000ul) : one;

    ulong exact;
    if (soft_pow_exact(xMagnitude, y, negative, roundingMode, flags, exact)) {
        return exact;
    }

    int e;
    soft_wide m = soft_log_split(soft_wide_from_f64(xMagnitude), e);
    soft_wide3 yw = soft_wide3_from_f64(y);
    soft_wide3 z = soft_wide3_add(
        soft_wide3_mul(yw, soft_wide3_from_int(e)),
        soft_wide3_mul(yw, soft_pow_log2_reduced(m))
    );
    // |z| >= 2048 overflows or lies far below half the smallest subnormal.
    // (1.5 + 2^-65) 2^(+-4096) stands in for the result: like it, it lies
    // far from every binary64 value and midpoint, so the rounding is
    // certified in every mode.
    if (z.exponent > 11) {
        soft_wide extreme = soft_wide{
            3ul << 62, 1ul << 63, z.sign ? -4096 : 4096, negative
        };
        return soft_wide_to_f64_status(extreme, roundingMode, flags, certified);
    }
    // |z| < 2^-60: 2^z lies within 2^-60 of 1 and is never exactly 1, so the
    // result is 1 or its neighbour, by the exp argument.
    if (z.exponent < -59) {
        ulong base = negative ? (one | 0x8000000000000000ul) : one;
        return soft_round_beside(base, z.sign == negative, roundingMode, flags);
    }
    int k = soft_wide3_round_to_int(z);
    soft_wide r = soft_wide3_to_wide(soft_wide3_sub(z, soft_wide3_from_int(k)));
    soft_wide value = soft_wide_scale2(soft_exp_poly(soft_wide_mul(r, SOFT_LOG_LN2)), k);
    value.sign = negative;
    return soft_wide_to_f64_status(value, roundingMode, flags, certified);
}
