// M9 correctly rounded binary64 sin, cos, and tan.
//
// Reduction. |x| <= pi/4 is used as is. Above that, x = M 2^E with M a 53-bit
// integer is reduced by Payne-Hanek: x (2/pi) = q + f with q an integer and
// |f| <= 1/2, and r = f pi/2. Only q mod 4 and f matter, so the product is
// formed with five 64-bit words of 2/pi starting at word k0 = floor((E-2)/64):
// every earlier word contributes a multiple of 4. The 384-bit product is
// exact; omitting the words after the fifth leaves it below the true value by
// under 2^53 2^(E - 64 k0 - 320) <= 2^-202 absolute.
//
// tools/m9/generate-trig-constants.py establishes, by a continued-fraction
// search over every exponent, that x (2/pi) is never within 2^-61.5 of an
// integer for binary64 x >= pi/4 (the closest is 6381956970095103 2^797), so
// |f| > 2^-61.5 and the omitted words cost under 2^-140.5 relative. Keeping
// 128 bits of f, the 128-bit pi/2, and the product f pi/2 add 2^-127 each, so
// r has relative error below 2^-125.4.
//
// Evaluation, at |r| <= pi/4, z = r^2 <= 0.617:
//
//     sin r = r * sum_{k=0..15} (-1)^k z^k / (2k+1)!,  tail < 2^-133.9 relative,
//     cos r =     sum_{k=0..16} (-1)^k z^k / (2k)!,    tail < 2^-139.1 relative.
//
// A running error bound over the Horner steps at z = (pi/4)^2, each truncating
// by at most 2^-127 relative, gives under 2^-125.7 for the sine sum and
// 2^-125.1 for the cosine. A relative error e in r moves sin r by at most e
// relative and cos r by at most r tan(r) e <= 0.79 e. So sin and cos are
// within 2^-124.3 relative, and tan = sin / cos (or -cos / sin), with the
// division's 2^-124.6, within 2^-122.8, against the 2^-116 certification
// margin.
//
// Closed forms: for nonzero |x| < 2^-27, sin(x) = x - x^3/6 and
// tan(x) = x + x^3/3 lie within x^2/3 < 2^-54 relative of x, strictly toward
// and away from zero respectively, and cos(x) = 1 - x^2/2 lies strictly
// between 1 - 2^-55 and 1; the same holds for cos r on a cosine branch
// after reduction, which the hardest arguments need. sin, cos, and tan of a nonzero algebraic number
// are transcendental (Lindemann-Weierstrass), so no other result is on the
// binary64 grid or a midpoint.

// Generated by tools/m9/generate-trig-constants.py. Do not edit by hand.
// 2/pi to 1280 bits, cross-checked against mpmath; word k holds bits
// 64k+1 .. 64k+64 after the binary point, truncated.
constant ulong SOFT_TRIG_TWO_OVER_PI[20] = {
    0xa2f9836e4e441529ul, 0xfc2757d1f534ddc0ul,
    0xdb6295993c439041ul, 0xfe5163abdebbc561ul,
    0xb7246e3a424dd2e0ul, 0x06492eea09d1921cul,
    0xfe1deb1cb129a73eul, 0xe88235f52ebb4484ul,
    0xe99c7026b45f7e41ul, 0x3991d639835339f4ul,
    0x9c845f8bbdf9283bul, 0x1ff897ffde05980ful,
    0xef2f118b5a0a6d1ful, 0x6d367ecf27cb09b7ul,
    0x4f463f669e5fea2dul, 0x7527bac7ebe5f17bul,
    0x3d0739f78a5292eaul, 0x6bfb5fb11f8d5d08ul,
    0x56033046fc7b6babul, 0xf0cfbc209af4361dul,
};

constant soft_wide SOFT_TRIG_RECIPROCAL_FACTORIAL[33] = {
    soft_wide{0x8000000000000000ul, 0x0000000000000000ul, 1, false},  // 1/0!
    soft_wide{0x8000000000000000ul, 0x0000000000000000ul, 1, false},  // 1/1!
    soft_wide{0x8000000000000000ul, 0x0000000000000000ul, 0, false},  // 1/2!
    soft_wide{0xaaaaaaaaaaaaaaaaul, 0xaaaaaaaaaaaaaaaaul, -2, false},  // 1/3!
    soft_wide{0xaaaaaaaaaaaaaaaaul, 0xaaaaaaaaaaaaaaaaul, -4, false},  // 1/4!
    soft_wide{0x8888888888888888ul, 0x8888888888888888ul, -6, false},  // 1/5!
    soft_wide{0xb60b60b60b60b60bul, 0x60b60b60b60b60b6ul, -9, false},  // 1/6!
    soft_wide{0xd00d00d00d00d00dul, 0x00d00d00d00d00d0ul, -12, false},  // 1/7!
    soft_wide{0xd00d00d00d00d00dul, 0x00d00d00d00d00d0ul, -15, false},  // 1/8!
    soft_wide{0xb8ef1d2ab6399c7dul, 0x560e4472800b8ef1ul, -18, false},  // 1/9!
    soft_wide{0x93f27dbbc4fae397ul, 0x780b69f5333c725bul, -21, false},  // 1/10!
    soft_wide{0xd7322b3faa271c7ful, 0x3a3f25c1bee38f10ul, -25, false},  // 1/11!
    soft_wide{0x8f76c77fc6c4bdaaul, 0x26d4c3d67f425f60ul, -28, false},  // 1/12!
    soft_wide{0xb092309d43684be5ul, 0x1c198e91d7b4269dul, -32, false},  // 1/13!
    soft_wide{0xc9cba54603e4e905ul, 0xd6f8a2efd1f27546ul, -36, false},  // 1/14!
    soft_wide{0xd73f9f399dc0f88eul, 0xc32b58774657f48ful, -40, false},  // 1/15!
    soft_wide{0xd73f9f399dc0f88eul, 0xc32b58774657f48ful, -44, false},  // 1/16!
    soft_wide{0xca963b81856a5359ul, 0x3028cbbb8d7ff53bul, -48, false},  // 1/17!
    soft_wide{0xb413c31dcbecbbddul, 0x8024435161554bc3ul, -52, false},  // 1/18!
    soft_wide{0x97a4da340a0ab926ul, 0x50f61dbdcb3a5abful, -56, false},  // 1/19!
    soft_wide{0xf2a15d201011283dul, 0x4e5695fc785d5dfeul, -61, false},  // 1/20!
    soft_wide{0xb8dc77b6e7ab8c5ful, 0x78a37e77372290c2ul, -65, false},  // 1/21!
    soft_wide{0x8671cb6dbfc294a2ul, 0x86485bf99c763abbul, -69, false},  // 1/22!
    soft_wide{0xbb0da098b1c0cecbul, 0xdc3826ebfb13cc26ul, -74, false},  // 1/23!
    soft_wide{0xf96780cb97abbe65ul, 0x25a033e54ec51033ul, -79, false},  // 1/24!
    soft_wide{0x9f9e66e8b2fd46a7ul, 0x22520cbbb7885c49ul, -83, false},  // 1/25!
    soft_wide{0xc4742fe35272cd1cul, 0x790285d3580a4a33ul, -88, false},  // 1/26!
    soft_wide{0xe8d58e16e6751905ul, 0x4d0c78aea13b9a50ul, -93, false},  // 1/27!
    soft_wide{0x850c5131a842e9b9ul, 0xe2e28e1aa546a152ul, -97, false},  // 1/28!
    soft_wide{0x92cfcc5a1ac56bd5ul, 0xf1873bb378948eb3ul, -102, false},  // 1/29!
    soft_wide{0x9c9962823eb07306ul, 0x56f6a614c4e2ba58ul, -107, false},  // 1/30!
    soft_wide{0xa1a6973c1fade217ul, 0x0f7237d35fe1c89dul, -112, false},  // 1/31!
    soft_wide{0xa1a6973c1fade217ul, 0x0f7237d35fe1c89dul, -117, false},  // 1/32!
};
constant int SOFT_TRIG_SIN_TERMS = 15;
constant int SOFT_TRIG_COS_TERMS = 16;
// truncated series tails at |r| <= pi/4: sine < 2^-133.9 relative,
// cosine < 2^-139.1 relative
// min |x - k pi/2| over binary64 x >= pi/4: > 2^-60.9
// (x 2/pi within 2^-61.5 of an integer, at exponent 797)

// Adds `value` into limb `index` of a little-endian 384-bit integer.
inline void soft_trig_accumulate(thread ulong *limbs, uint index, ulong value) {
    for (; index < 6u && value != 0ul; ++index) {
        ulong sum = limbs[index] + value;
        value = ulong(sum < value);
        limbs[index] = sum;
    }
}

// Shifts a little-endian 384-bit integer left by `distance` bits, discarding
// the bits that leave the top, never shifting a 64-bit limb by 64.
inline void soft_trig_shift_left384(thread ulong *limbs, uint distance) {
    uint whole = distance / 64u;
    uint bits = distance % 64u;
    for (int index = 5; index >= 0; --index) {
        int source = index - int(whole);
        ulong value = 0ul;
        if (source >= 0) {
            value = limbs[source] << bits;
            if (bits != 0u && source >= 1) value |= limbs[source - 1] >> (64u - bits);
        }
        limbs[index] = value;
    }
}

// Reduces a finite positive binary64 |x| > pi/4 to r = x - q pi/2, returning
// r and q mod 4.
inline soft_wide soft_trig_reduce_large(ulong magnitude, thread uint &quadrant) {
    soft_normalized x = soft_normalize_operand(
        uint(magnitude >> 52), magnitude & 0x000ffffffffffffful
    );
    int E = x.exponent - 1075;  // |x| = M 2^E
    int k0 = E >= 2 ? (E - 2) / 64 : 0;
    int d = E - 64 * (k0 + 1);  // the product's units bit is bit 256 - d

    ulong limbs[6] = {0ul, 0ul, 0ul, 0ul, 0ul, 0ul};
    for (uint j = 0u; j < 5u; ++j) {
        ulong word = SOFT_TRIG_TWO_OVER_PI[k0 + int(j)];
        soft_trig_accumulate(limbs, 4u - j, x.significand * word);
        soft_trig_accumulate(limbs, 5u - j, mulhi(x.significand, word));
    }

    uint units = uint(256 - d);
    uint q = 0u;
    for (uint bit = 0u; bit < 2u; ++bit) {
        uint position = units + bit;
        q |= uint((limbs[position / 64u] >> (position % 64u)) & 1ul) << bit;
    }

    // Move the fraction to the top: bit 383 now has weight 1/2.
    soft_trig_shift_left384(limbs, 384u - units);
    bool negative = (limbs[5] >> 63) != 0ul;
    if (negative) {  // f >= 1/2: take q + 1 and f - 1
        q += 1u;
        ulong carry = 1ul;
        for (uint index = 0u; index < 6u; ++index) {
            ulong value = ~limbs[index] + carry;
            carry = ulong(carry != 0ul && value == 0ul);
            limbs[index] = value;
        }
    }
    quadrant = q & 3u;

    uint leading = 0u;
    for (int index = 5; index >= 0 && limbs[index] == 0ul; --index) leading += 64u;
    if (leading < 384u) leading += uint(clz(limbs[5 - int(leading / 64u)]));
    soft_trig_shift_left384(limbs, leading);
    soft_wide f = soft_wide{limbs[5], limbs[4], -int(leading), negative};
    return soft_wide_mul(f, SOFT_ATAN_PI_2);
}

// pi/4 rounded down to binary64; arguments at or below it are not reduced.
constant ulong soft_trig_pi_4_bits = 0x3fe921fb54442d18ul;

inline soft_wide soft_trig_reduce(ulong magnitude, thread uint &quadrant) {
    if (magnitude <= soft_trig_pi_4_bits) {
        quadrant = 0u;
        return soft_wide_from_f64(magnitude);
    }
    return soft_trig_reduce_large(magnitude, quadrant);
}

inline soft_wide soft_trig_sin(soft_wide r, soft_wide z) {
    soft_wide accumulator = SOFT_TRIG_RECIPROCAL_FACTORIAL[2 * SOFT_TRIG_SIN_TERMS + 1];
    for (int term = SOFT_TRIG_SIN_TERMS - 1; term >= 0; --term) {
        accumulator = soft_wide_sub(
            SOFT_TRIG_RECIPROCAL_FACTORIAL[2 * term + 1], soft_wide_mul(z, accumulator)
        );
    }
    return soft_wide_mul(r, accumulator);
}

inline soft_wide soft_trig_cos(soft_wide z) {
    soft_wide accumulator = SOFT_TRIG_RECIPROCAL_FACTORIAL[2 * SOFT_TRIG_COS_TERMS];
    for (int term = SOFT_TRIG_COS_TERMS - 1; term >= 0; --term) {
        accumulator = soft_wide_sub(
            SOFT_TRIG_RECIPROCAL_FACTORIAL[2 * term], soft_wide_mul(z, accumulator)
        );
    }
    return accumulator;
}

// |x| < 2^-27, nonzero, as for atan.
constant uint soft_trig_tiny_exponent_field = 996u;

// A reduced |r| < 2^-27 on a cosine branch: cos r = 1 - r^2/2 + ... lies
// strictly between 1 - 2^-55 and 1, so the result is +-1 or its neighbour
// toward zero. The hardest arguments reach |r| near 2^-61, where cos r is
// within 2^-116 of 1 and could never be certified. The test is on the
// computed r, whose relative error of 2^-125.4 leaves the true r^2/2 below
// 2^-55 as well.
inline bool soft_trig_near_one(soft_wide r) {
    return r.exponent <= -27;
}

inline ulong soft_trig_round_one(bool negative, uint roundingMode, thread uint &flags) {
    ulong one = negative ? 0xbff0000000000000ul : 0x3ff0000000000000ul;
    return soft_round_beside(one, negative, roundingMode, flags);
}

// NaNs and infinities, shared by sin, cos, and tan. Returns true when decided.
inline bool soft_trig_special(ulong a, thread ulong &result, thread uint &flags) {
    if (soft_is_nan(a)) {
        if (soft_is_signaling_nan(a)) flags |= soft_flag_invalid;
        result = a | 0x0008000000000000ul;
        return true;
    }
    if ((a & 0x7ffffffffffffffful) == 0x7ff0000000000000ul) {
        flags |= soft_flag_invalid;
        result = 0x7ff8000000000000ul;
        return true;
    }
    return false;
}

inline ulong soft_sin64_certified(
    ulong a, uint roundingMode, thread uint &flags, thread bool &certified
) {
    certified = true;
    ulong special;
    if (soft_trig_special(a, special, flags)) return special;
    ulong magnitude = a & 0x7ffffffffffffffful;
    bool sign = (a >> 63) != 0ul;
    if (magnitude == 0ul) return a;
    if (uint(magnitude >> 52) < soft_trig_tiny_exponent_field) {
        return soft_round_beside(a, sign, roundingMode, flags);
    }
    uint quadrant;
    soft_wide r = soft_trig_reduce(magnitude, quadrant);
    bool negative = ((quadrant & 2u) != 0u) != sign;
    if ((quadrant & 1u) != 0u && soft_trig_near_one(r)) {
        return soft_trig_round_one(negative, roundingMode, flags);
    }
    soft_wide z = soft_wide_mul(r, r);
    soft_wide value = (quadrant & 1u) != 0u ? soft_trig_cos(z) : soft_trig_sin(r, z);
    return soft_wide_to_f64_status(
        soft_wide_negate_if(value, negative), roundingMode, flags, certified
    );
}

inline ulong soft_cos64_certified(
    ulong a, uint roundingMode, thread uint &flags, thread bool &certified
) {
    certified = true;
    ulong special;
    if (soft_trig_special(a, special, flags)) return special;
    ulong magnitude = a & 0x7ffffffffffffffful;
    if (magnitude == 0ul) return 0x3ff0000000000000ul;
    if (uint(magnitude >> 52) < soft_trig_tiny_exponent_field) {
        return soft_round_beside(0x3ff0000000000000ul, false, roundingMode, flags);
    }
    uint quadrant;
    soft_wide r = soft_trig_reduce(magnitude, quadrant);
    // cos(r + q pi/2) is cos r, -sin r, -cos r, sin r for q = 0, 1, 2, 3.
    bool negative = quadrant == 1u || quadrant == 2u;
    if ((quadrant & 1u) == 0u && soft_trig_near_one(r)) {
        return soft_trig_round_one(negative, roundingMode, flags);
    }
    soft_wide z = soft_wide_mul(r, r);
    soft_wide value = (quadrant & 1u) != 0u ? soft_trig_sin(r, z) : soft_trig_cos(z);
    return soft_wide_to_f64_status(
        soft_wide_negate_if(value, negative), roundingMode, flags, certified
    );
}

inline ulong soft_tan64_certified(
    ulong a, uint roundingMode, thread uint &flags, thread bool &certified
) {
    certified = true;
    ulong special;
    if (soft_trig_special(a, special, flags)) return special;
    ulong magnitude = a & 0x7ffffffffffffffful;
    bool sign = (a >> 63) != 0ul;
    if (magnitude == 0ul) return a;
    if (uint(magnitude >> 52) < soft_trig_tiny_exponent_field) {
        return soft_round_beside(a, !sign, roundingMode, flags);
    }
    uint quadrant;
    soft_wide r = soft_trig_reduce(magnitude, quadrant);
    soft_wide z = soft_wide_mul(r, r);
    soft_wide s = soft_trig_sin(r, z);
    soft_wide c = soft_trig_cos(z);
    // tan(r + q pi/2) is tan r for even q and -1/tan r for odd q.
    soft_wide value = (quadrant & 1u) != 0u
        ? soft_wide_negate_if(soft_wide_div(c, s), true)
        : soft_wide_div(s, c);
    return soft_wide_to_f64_status(
        soft_wide_negate_if(value, sign), roundingMode, flags, certified
    );
}
